name: Linux

on: [push]

env:
  BUILD_CONFIGURATION: Release

jobs:
  ice_so_and_client_so:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    # Alternative:
    # sudo apt install linux-libc-dev
    # sudo apt-get -f install
    # sudo apt install gcc-4.8

    - name: Update sources to include xenial main
      run: sudo su -c "echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial main' >> /etc/apt/sources.list"

    - name: Update sources to include xenial universe
      run: sudo su -c "echo 'deb http://us.archive.ubuntu.com/ubuntu/ xenial universe' >> /etc/apt/sources.list"

    - name: Update packages
      run: sudo apt update -y

    - name: Install make
      run: sudo apt-get install make

    - name: Install g++-4.8
      run: sudo apt install g++-4.8 gcc-4.8 -y

    - name: Install headers
      run: sudo apt-get install gcc-4.8-multilib g++-4.8-multilib -y

    - name: Build ice.so
      working-directory: ./linux
      run: make hl CFG=${{env.BUILD_CONFIGURATION}}

    - name: Build client.so
      working-directory: ./linux
      run: make hl_cdll CFG=${{env.BUILD_CONFIGURATION}}

    - name: Upload client.so
      uses: actions/upload-artifact@v3
      with:
        name: client.so
        path: ./linux/Release/client.so
