name: macOS

on: [push]

env:
  BUILD_CONFIGURATION: Release

jobs:
  ice_dylib_and_client_dylib:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build ice.dylib
      working-directory: ./linux
      run: make hl CFG=${{env.BUILD_CONFIGURATION}}

    - name: Build client.dylib
      working-directory: ./linux
      run: make hl_cdll CFG=${{env.BUILD_CONFIGURATION}}
