name: macOS

on: [push]

env:
  BUILD_CONFIGURATION: Release

jobs:
  ice_dylib_and_client_dylib:
    runs-on: macOS-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Where is clang?
      run: xcodebuild -find clang && /Applications/Xcode_12.4.app/Contents/Developer/usr/bin/clang

    - name: Build ice.dylib
      working-directory: ./linux
      run: make hl CFG=${{env.BUILD_CONFIGURATION}}

    - name: Build client.dylib
      working-directory: ./linux
      run: make hl_cdll CFG=${{env.BUILD_CONFIGURATION}}
