name: macOS

on: [push]

env:
  BUILD_CONFIGURATION: Release

jobs:
  ice_dylib_and_client_dylib:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'

    - name: What again?
      run: sudo xcode-select -p

    - name: Install MacOSX10.8.sdk
      run: |
        mkdir /tmp/sdk
        cd /tmp/sdk
        curl -sSL https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.8.sdk.tar.xz > sdk.tar
        tar -xvf sdk.tar
        sudo ln -s /tmp/sdk/MacOSX10.8.sdk $(/usr/bin/xcode-select -print-path)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk
        rm sdk.tar

    - name: Build ice.dylib
      working-directory: ./linux
      run: make hl CFG=${{env.BUILD_CONFIGURATION}}

    - name: Build client.dylib
      working-directory: ./linux
      run: make hl_cdll CFG=${{env.BUILD_CONFIGURATION}}
